version: '3.4'
services:
  db:
    image: postgres:10
    volumes:
      - crunchbase-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
  api:
    build: https://github.com/ericparshall/the645test.git
    image: the645test
    command: bash -c "rails db:setup && rails s -p 3000 -b '0.0.0.0'"
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DISABLE_FILE_WATCHER: true
      RAILS_LOG_TO_STDOUT: true
    depends_on:
      - db
  app:
    build: .
    image: crunchinator9000
    command: bash -c "rails db:prepare && rails db:setup && rails s -p 3000 -b '0.0.0.0'"
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "9000:3000"
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DISABLE_FILE_WATCHER: true
      RAILS_LOG_TO_STDOUT: true
    depends_on:
      - db
      - api
volumes:
  crunchbase-data:
    name: crunchbase-postgres-data
    driver: local
